### ISSUE TITLE
No U of A access/has U of A access

### ISSUE THREAD

**Issue by merisjames** [ualbertalib/discovery#538]
Results under "Books and More"
https://search.library.ualberta.ca/catalog/443607 
https://search.library.ualberta.ca/catalog/816237
are labelled "Note: No University of Alberta Access. On-campus access allowed at the following locations:" Available location is U of A. We do indeed have access (via Heinonline and others).
A number of journals have an additional entry under "Electronic Journals" such as https://search.library.ualberta.ca/catalog/110978977730513 These entries don't state what subscribers have access via which service, which will probably be confusing for users, as some subscriptions will work for some people, and others won't

**Comment by redlibrarian** [comment]
I'm working on this now as part of the broader holdings/links logic. This will be fixed in the next release.

**Comment by redlibrarian** [comment]
I'm just capturing here that the logic in https://github.com/ualbertalib/discovery/blob/master/app/views/catalog/show.html.erb
Is really ugly - needs to be simplified and the logic straightened out.

**Comment by redlibrarian** [comment]
I've broken the code out into it's own template to make it easier to work with:
https://github.com/ualbertalib/discovery/blob/master/app/views/catalog/_urls.html.erb

**Comment by redlibrarian** [comment]
OK, this is fixed. Should be visible and correct in the next code release.

**Comment by merisjames** [comment]
Seems to be fixed, with the already? noted caveat that the whole big long link resolver url is visible.

**Comment by redlibrarian** [comment]
Yes - I've asked @nnunn about that in the other issue. I'm going to close this issue, since the original problem has been fixed. Thanks.

**Comment by scastell** [comment]
am opening as I've come across a few records that include the following note

No University of Alberta Access. On-campus access allowed at the following locations:

but then don't include the locations

see
https://search.library.ualberta.ca/catalog/6763785
https://search.library.ualberta.ca/catalog/6517896
https://search.library.ualberta.ca/catalog/6714214
as examples

There are a number of related items (#636, #600) - apologies if I put it under the wrong issue

**Comment by redlibrarian** [comment]
@merisjames None of these resources are still in the catalogue, so there are no holdings. These (deleted) records should be automatically removed from the Blacklight index, but we don't have that going yet...

**Comment by scastell** [comment]
the first 2 still appear to be in the catalogue, you're right @redlibrarian the 3rd one is gone

http://www.library.ualberta.ca/permalink/opac/7234968/WUAARCHIVE 

http://www.library.ualberta.ca/permalink/opac/7221955/WUAARCHIVE

**Comment by redlibrarian** [comment]
@scastell Interestingly, those are the same titles, but not the same records (you can tell by comparing the IDs in the four URLs). The records that the Blacklight URLs refer to are all gone from Symphony, but it looks like the titles are there under new IDs. This too should be rectified when we have our reindexing going nightly.

**Comment by scastell** [comment]
aha, I finally get it. Thanks. Closing.
