### ISSUE TITLE
Placing hold error

### ISSUE THREAD

**Issue by hannepearce** [ualbertalib/discovery#638]
I'm hoping this isn't an old issue that I've missed, I did a search but didn't find one that was similar. When I try to place a hold on a book I get an error "ITEM database ERROR" on the select a library screen. 
![2015-10-16_11-52-06](https://cloud.githubusercontent.com/assets/14892833/10549470/776f9886-73fe-11e5-9991-45acea5defb4.jpg)

I'm not sure if it's related to the problem of location, library and item type not appearing in the record but this is the book I'm trying to place a hold on.
![2015-10-16_11-53-56](https://cloud.githubusercontent.com/assets/14892833/10549488/97cab71e-73fe-11e5-98b5-261bc7ca13be.jpg)

**Comment by redlibrarian** [comment]
It shouldn't be related to the location, etc, not showing up (which will be fixed in the new code). @jhennig can you look into this?

**Comment by jhennig** [comment]
Thanks for the screenshot.

The catalog key in the place hold button on search.library is: 000043925273  I think this is wrong.
Shouldn't it be:  6924509 ? This is the 001 field.  I have no idea where: 000043925273  is coming from. 

Jeremy

**Comment by redlibrarian** [comment]
Interesting. I can see it in the solr index and it's coming from Symphony, but it's not a standard Symphony catkey. This might be the same problem as catkeys that we see starting with "ocn" - we get a brief record that gets put into the catalogue with its default ID (from the vendor or publisher), then we overlay a real record when we get one, giving it a correct Symphony catkey. These should be caught and fixed automatically, but I think our nightly updating isn't working so some of these are falling through the cracks. This should fix itself soon, but let's keep an eye on it.

**Comment by hannepearce** [comment]
I have tried placing a hold on this book today and I still can't achieve it in blacklight.
![university_of_alberta_libraries 2](https://cloud.githubusercontent.com/assets/14892833/10673446/1ab7d018-78b3-11e5-95dc-5b635dd5ad05.jpg)
also, it appears the holdings information is missing. The ebook record is showing holdings just fine.
![university_of_alberta_libraries](https://cloud.githubusercontent.com/assets/14892833/10673466/3a870ab2-78b3-11e5-83cf-79993c09d47a.jpg)

**Comment by hannepearce** [comment]
This issue appears resolved. Was able to place a hold on several titles earlier today.
