### ISSUE TITLE
Articles search, EDS switching to French

### ISSUE THREAD

**Issue by fculpepper** [ualbertalib/discovery#697]
I did a search from the main search box, "bodybuilding", and selected Articles. The results page is in English:
![image](https://cloud.githubusercontent.com/assets/14892870/11009115/286da562-8492-11e5-810a-b523e5dc7a1f.png)

But when I click on any of the results, the record in EDS is in French:
![image](https://cloud.githubusercontent.com/assets/14892870/11009062/da922cb4-8491-11e5-8953-93eac16f76d5.png)

**Comment by redlibrarian** [comment]
Hmm. I can't replicate this. @ualbertalib/discovery-testing has anyone else noticed this?

**Comment by theLinkResolver** [comment]
The same things happens for me.

**Comment by redlibrarian** [comment]
@fculpepper @theLinkResolver Not sure how to investigate. Scott, I'll come up and see you. Can you both tell me which browser you're using?

**Comment by fculpepper** [comment]
Chrome

**Comment by fculpepper** [comment]
Tried it out in Firefox too, got a no results error the first 2 times. 3rd attempt gave me results and the EDS records are in French

**Comment by redlibrarian** [comment]
Thanks @fculpepper . That's really weird, but @theLinkResolver had the same problem (down to the first two searches returning no results). Strange - I'll have to look into it.

**Comment by redlibrarian** [comment]
@fculpepper @theLinkResolver I'm hoping this was a glitch on EDS' end on Friday. Can you try these searches again and let me know if the problem is still happening? Thanks.

**Comment by fculpepper** [comment]
When I open an article from the bento results screen, EDS is in French. But when I go to the Article results page (different results than bento) and open an article from there, it's in English.

**Comment by theLinkResolver** [comment]
Same for me (and that difference between result sets is concerning).

**Comment by redlibrarian** [comment]
This is exceedingly bizarre. From this list of results, https://search.library.ualberta.ca/results?utf8=%3F&q=toynbee+convector every other result goes to the English interface (even-numbered results). Because we use HTML templates, every result uses the same link to get to the EDS page. So I can't see why this would be happening.

**Comment by redlibrarian** [comment]
As for the result count discrepancy, I think I've figured out & fixed that. It should be fixed in the next release.

**Comment by redlibrarian** [comment]
This looks like an EDS issue. The links that we're using have nothing in them specifying a language for the interface. Somehow EDS is redirecting those links to the French interface. I don't think this is a *huge* problem, so I am going to mark it as low priority, and look into it in the next phase.

**Comment by redlibrarian** [comment]
@theLinkResolver Is this still happening, do you know?

**Comment by theLinkResolver** [comment]
@redlibrarian Unfortunately, I still had this occur when I tested out your Toynbee Convector example. It wasn't quite as patterned (even vs. odd numbered results) as you described above, though. But it's still happening.

**Comment by scastell** [comment]
also happened yesterday, and today, when I was searching for "complete patent kit". All 3 EDS search results go to the french interface.

https://www.library.ualberta.ca/results?utf8=%3F&q=%22complete+patent+kit%22

**Comment by theLinkResolver** [comment]
This is still happening - e.g. in @linds37 training session today
