### ISSUE TITLE
[Discovery] Fix deletes

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#932]
This is one of the most important issues. We need to know that records that come through marked for deletion are, in fact, being deleted from the index. I found this tricky to do - probably something I'm missing, but also because our Symphony records don't use standard MARC practice for this.

Done when:

- [ ] Deletion logic is in place and tested
- [ ] Deleted records are removed from production one day after being deleted/shadowed in Symphony.
Will likely have to work with Jim on this one.

**Comment by redlibrarian** [comment]
I just figured out how to test symphony deletes, and it seems to be working. I may not understand precisely how the Symphony records are being marked for deletion. I'll have to check with Jim.

As for the SFX and database records, since we do a *full* ingest every night, the plan is to simply delete everything from those indexes before reingesting.

**Comment by redlibrarian** [comment]
OK, from what I can tell Symphony deletes are working, but there's a misunderstanding of how records in Symphony are being recognized and tagged as requiring deletion. We should look at this in the summer with Jim. For Databases and SFX, I've added the logic to wipe out those records before reingesting. We'll check it in the next release, and then this issue can be closed.

**Comment by theLinkResolver** [comment]
@redlibrarian 
@ualbertalib/serials-cataloguing noted two things today that suggest the records do not reflect yesterday's changes.

[This record](https://www.library.ualberta.ca/catalog/954921346233) shouldn't be in the system today, because we turned off its only active portfolio yesterday.

[This record](https://www.library.ualberta.ca/catalog/991042732696152) is not in the system, but should be, as we activated a portfolio in it yesterday.

(disregard the fact that they have the same title - metadata weirdness)

**Comment by redlibrarian** [comment]
This is a really hard thing to test. At some point this summer, let's sit down and work out some way of adequately testing this data pipeline.

**Comment by theLinkResolver** [comment]
@redlibrarian For the record, those records are in the system now. (Wasn't around yesterday to test.) Happy to help with developing tests, for sure.

**Comment by theLinkResolver** [comment]
@redlibrarian Correction/braincramp - the first record is gone and the second record is there -- and that's the way it should be!!

**Comment by redlibrarian** [comment]
Ha ha - OK, so the answer to "are the deletes working?" is: maybe!?

On Fri, May 6, 2016 at 3:19 PM, Scott Davies <notifications@github.com>
wrote:

> @redlibrarian <https://github.com/redlibrarian> Correction/braincramp -
> the first record is gone and the second record is there -- and that's the
> way it should be!!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/discovery/issues/932#issuecomment-217561127>
>



-- 
Fender F-35
Ibanez M522SBS
Cordoba 45FP
Lafferty LB

**Comment by theLinkResolver** [comment]
@redlibrarian I just don't get why it took more than one day, if you delete all and then reingest nightly. Did it have something to do with the full SFX2Sirsi update running? Was the Wednesday SFX file not available for some reason? (Really grasping at straws!)

**Comment by redlibrarian** [comment]
This still isn't working. I need to take a step back and figure out how to **test** this, I think.

**Comment by theLinkResolver** [comment]
@redlibrarian A fresh example for this.

https://www.library.ualberta.ca/catalog/5532354

This record was marked discard on Aug. 4 and purged on Aug. 5, but it's still hanging around. (Although, it's not in search-test.)

**Comment by redlibrarian** [comment]
@theLinkResolver There's an updated full index in test right now, which will be pushed to prod tomorrow morning. You're right though, this still needs to be addressed. I'm going to put this in the fall milestone.

**Comment by redlibrarian** [comment]
This is one of the most important issues. We need to know that records that come through marked for deletion are, in fact, being deleted from the index. I found this tricky to do - probably something I'm missing, but also because our Symphony records don't use standard MARC practice for this.

Done when:

- [ ] Deletion logic is in place and tested
- [ ] Deleted records are removed from production one day after being deleted/shadowed in Symphony.

Will likely have to work with Jim on this one.

**Comment by seanluyk** [comment]
Adding here as well so we don't miss it: 

Ingest includes items that **Do Not** have these locations
IN_PROCESS
UNKNOWN
MISSING
LOST
DISCARD
LOST-PAID
LONGOVRDUE
CANC_ORDER
ON_THE_FLY
LOST-ASSUM
LOST-CLAIM
INSHIPPING
STOR_DARK
STOR_RCRF

Titles that **Do Not** have a title for Tag 245

Exclude:
Shadowed Titles
Shadowed Call Numbers
Shadowed Items

**Comment by seanluyk** [comment]
In reference to @theLinkResolver's [comment](https://github.com/ualbertalib/discovery/issues/1190#issuecomment-418514042) about STOR_RCRF items appearing, I can confirm that excluding a location in Jim's script does not remove the items. For example: https://www.library.ualberta.ca/catalog/8223453 is still here. These only get fixed in the monthly re-ingest.

**Comment by seanluyk** [comment]
This still a spike - we need to understand the ingest process end to end to diagnose the problem.

**Comment by seanluyk** [comment]
From discussing the question of deletes with bib services, I think we're missing a crucial step in our ingest workflow unless I'm mistaken:

 - Once an item has been deleted/has no holdings attached to it, it wouldn't be coming through in our nightly ingest, so there would be no way for us to know that it had been deleted, which is why the record would still appear until the index gets wiped out on the monthly ingest. In other words, the problem isn't that deleted records are coming in, they aren't coming out
 - We probably need to do an extra step which would be to get a nightly report of deleted records, which would populate a script with the catkeys for items that need to be deleted from the SOLR index

**Comment by seanluyk** [comment]
Deletion script needs to also account for shadowed locations specified above, and any others that may have been missed

**Comment by pgwillia** [comment]
Here's something related to deletes https://github.com/ualbertalib/discovery/blob/master/config/SolrMarc/symphony_index.properties#L167-L169

**Comment by seanluyk** [comment]
Sample record: deleted in Symphony https://library.ualberta.ca/catalog/1236269

**Comment by seanluyk** [comment]
@seanluyk to Neil about possibilities for doing this on his end

**Comment by seanluyk** [comment]
Adding a fresh example of a record deleted from Symphony that still appears, reported to me by CSU: https://library.ualberta.ca/catalog/8295716

@weiweishi I think a natural next step in finally fixing this issue is getting the dev team together with someone on the eBooks team. @theLinkResolver just reading @pgwillia's comment above, any idea what the deletion logic is attempting to do? 000[5]?

**Comment by weiweishi** [comment]
@seanluyk I think so. I also think we should have Jim there as well, to see if this is something that can be tackled in his report generating script.

**Comment by seanluyk** [comment]
@weiweishi I don't think this is a Jim thing but I could be wrong. The problem here is that this item was deleted from Symphony yet the deletion logic in Blacklight didn't remove it/was never set up in the first place. We're not getting deleted items coming through in ingest, I'm 99% positive of that because the Discard location is excluded from Jim's export script. I think these cases all fall under this process described to me by Amanda in bib:

"The second way is when we run one of our batch reports called Ebook Deletes. This report sets the Current location of a holding to DISCARD and then an overnight report, set up by the ILS team, will delete the item holding."

AFAIK there is nothing added to the record that's telling Blacklight to delete it. The [stock logic](https://github.com/ualbertalib/discovery/blob/master/config/SolrMarc/symphony_index.properties#L167-L169) linked to by @pgwillia above probably won't work since I don't believe we use this practice to mark deleted items. I'll set up a meeting with everyone soon to figure this out!

**Comment by theLinkResolver** [comment]
@seanluyk The 000[5] would always have a character in it ([this is Leader position 05 btw](https://www.loc.gov/marc/bibliographic/bdleader.html)), so the bit about deleting a record if it's empty should never apply. I'm not sure how to interpret the rest of that snippet, but if it is perhaps looking for a "d" in 000[5] then that is a step to handling deletes. The thing is that, as discussed above, the feeling is that Jim is not supplying deleted or shadowed records.

I still wonder how deletes are being done for EDS, though - it seemed like we needed to mirror that process. It does involve some customization of the extract by Jim.

In the middle of the night when the extract happens (and before the discarded are actually deleted from the system outright), what we basically need is for Jim to supply all the records that have all items shadowed (be it missing/discarded/etc) with a 000[5]=d. Then upon ingest, if the logic is in place to interpret 000[5] as a deletion... 

I'm happy to attend a meeting to help get to the solution

**Comment by seanluyk** [comment]
@pgwillia thanks for investigating this. I confirmed with Jim today that a d is being added to the fifth character position in the leader, as per @theLinkResolver's suspicion. This is how items get flagged for deletion in the EBSCO Discovery Service. From the data files @nmacgreg sent, here is an example of a record that was deleted in the Dec. 16 ingest, with a d in the fifth character position:

=LDR  01082dam a2200349Ki 4500
=001  8362143
=003  OCoLC
=005  20181012141156.5
=008  180224s2018\\\\onc\\\\\\\\\\\000\0\eng\d
=020  \\$a0771047150$qhardcover
=020  \\$a9780771047152$qhardcover
=035  \\$aon1023860069
=040  \\$aYDX$beng$erda$cYDX$dTOH$dYDX$dAEU
=043  \\$an-cn---
=050  \4$aF1008$b.J64 2018
=082  04$a971$223
=090  \\$aF 1008 J64 2018$bAEKC
=100  1\$aJohnston, David,$d1941-$eauthor.
=245  10$aTrust :$btwenty ways to build a better country /$cDavid Johnston.
=250  \\$aHardcover edition.
=264  \1$a[Toronto] :$bSignal/McClelland & Stewart,$c2018.
=300  \\$ax, 218 pages ;$c22 cm
=336  \\$atext$btxt$2rdacontent
=337  \\$aunmediated$bn$2rdamedia
=338  \\$avolume$bnc$2rdacarrier
=596  \\$a31
=650  \0$aEthics$zCanada.
=650  \0$aTrust.
=651  \0$aCanada.
=949  \\$hSKING-RF-B
=945  \\$a1079010$fBK-HM-HIST$hNO_LOAN$l31.59
=926  \\$aF 1008 J64 2018$wLC$c1$i8362143-1001$lDISCARD$mKINGS$rY$sY$tNO_LOAN$u11/14/2018

**Comment by pgwillia** [comment]
Method:
1. for each of the nightly files I have copy to the location specified by the ingest script and run it capturing the output
```
for fileday in D181210 D181211 D181212 D181213 D181214 D181215 D181216 D181218
do
  cp ../Marc/DeleteProject/UADATA.D181209 data/big-sample.mrc
  bundle exec rake ingest['symphony'] &> ../Marc/DeleteProject/solrmarc_deletes.D181210.txt
done
```
2. manually parse the Solr log for chunks containing delete (i.e. `solr_1         | 2018-12-18 22:34:39.855 INFO  (qtp1595212853-46) [   x:discovery] o.a.s.u.p.LogUpdateProcessorFactory [discovery]  webapp=/solr path=/update params={wt=xml&version=2.2}{delete=[6733982 (-1620230778236436480)]} 0 0`) into solr_delete.*.txt files corresponding to the filedays above.

3. parse the two sets of files so that they only contain the identifiers, one per line

4. compare the two sets of delete batches
```
for fileday in D181210 D181211 D181212 D181213 D181214 D181215 D181216 D181218
do 
  diff -u solrmarc_deletes.$fileday.txt solr_deletes.$fileday.txt > $fileday.diff
done
```

Observations: no differences here.
```

**Comment by pgwillia** [comment]
@theLinkResolver I can provide a list of ids of what was deleted.  Can we compare this with any lists we have about items that should have been deleted? Hopefully this will reveal some that were missed that we can track down.
[solr_deletes.D181210.txt](https://github.com/ualbertalib/discovery/files/2696275/solr_deletes.D181210.txt)
[solr_deletes.D181211.txt](https://github.com/ualbertalib/discovery/files/2696276/solr_deletes.D181211.txt)
[solr_deletes.D181212.txt](https://github.com/ualbertalib/discovery/files/2696277/solr_deletes.D181212.txt)
[solr_deletes.D181213.txt](https://github.com/ualbertalib/discovery/files/2696278/solr_deletes.D181213.txt)
[solr_deletes.D181214.txt](https://github.com/ualbertalib/discovery/files/2696279/solr_deletes.D181214.txt)
[solr_deletes.D181215.txt](https://github.com/ualbertalib/discovery/files/2696280/solr_deletes.D181215.txt)
[solr_deletes.D181216.txt](https://github.com/ualbertalib/discovery/files/2696281/solr_deletes.D181216.txt)
[solr_deletes.D181218.txt](https://github.com/ualbertalib/discovery/files/2696282/solr_deletes.D181218.txt)

**Comment by pgwillia** [comment]
Here's Jim's scripts from Jul 9, 2018, 3:06 PM
https://gist.github.com/pgwillia/9f24bd40bc1c61e98a613e1fa974b8f7

Replying to @seanluyk  https://github.com/ualbertalib/discovery/issues/932#issuecomment-418514582
https://gist.github.com/pgwillia/9f24bd40bc1c61e98a613e1fa974b8f7#file-setdiscardtitle-pl-L100-L111
https://gist.github.com/pgwillia/9f24bd40bc1c61e98a613e1fa974b8f7#file-setdiscardtitle-pl-L138-L149
https://gist.github.com/pgwillia/9f24bd40bc1c61e98a613e1fa974b8f7#file-skipdiscardtitles-pl-L103-L118
https://gist.github.com/pgwillia/9f24bd40bc1c61e98a613e1fa974b8f7#file-skipdiscardtitles-pl-L145-L160

The version I have (from July) is missing `STOR_RCRF` everywhere and has `IN_PROCESS` missing in setDiscardTitles script.  Could this be the source of this problem?

**Comment by seanluyk** [comment]
@pgwillia I'm pretty sure that Jim added stor_rcrf sometime later, and in_process should have been there from the beginning. I don't think that this could be the source, but it would be good to confirm that these are excluded anyway. The deleted ebook titles wouldn't have these locations as far as I know

**Comment by theLinkResolver** [comment]
@pgwillia I can't personally provide any lists about past deletions but we might be make arrangements to track deletions for a period of time to accomplish this.

**Comment by seanluyk** [comment]
@pgwillia I think Peggy may be the best person to ask for a log of deletions - apparently we have the full history

**Comment by theLinkResolver** [comment]
@seanluyk indeed, although it's Jim's treatment of them that is likely the only way to track them, because he takes into account when a record is shadowed altogether vs. when things have been marked discard (you could use the logs to find things marked discard on a certain day but I'm not sure that they would tell you whether all items on a record were marked discard or not - only then would the record be shadowed/discarded, and I'm not sure that any data actually changes to indicate this - perhaps this is something to determine).

**Comment by seanluyk** [comment]
Thanks for your sleuthing, @pgwillia. As discussed this morning at our weekly ITS meeting, @weiweishi is going to set up a meeting with everyone involved in this issue to discuss next steps.

**Comment by theLinkResolver** [comment]
@seanluyk @weiweishi I can continue to be the Bib rep on this one. Jim and I work very closely on some things, and can speak each other's language effectively.

**Comment by weiweishi** [comment]
thanks Scott. We have a meeting scheduled for this afternoon to discuss
deletions and I've just sent you the meeting invite.


*Weiwei Shi*Digital Initiative Applications Librarian

2-10L Cameron Library, University of Alberta
780-492-7802  |  weiwei.shi@ualberta.ca
*"The University of Alberta respectfully acknowledges that we are situated
on Treaty 6 territory, traditional lands of First Nations and Métis
people."*

**Comment by weiweishi** [comment]
Additional information on deletion:

- E-records are deleted daily

- physical records are deleted monthly with a discard report.  Before the deletion, the titles are set as "shadowed"/"discarded", but not being removed from the Symphony system. We will move to weekly deletion at the end of the month. 

- There are different scenarios for an item (holdings) or a record (title) to be shadowed (missing, dark archives, discarded etc)

From the Discovery Services perspective, all of these should be treated equally, we don't want to display anything that the public users should not see, despite their different scenarios. 

Based on @pgwillia's investigation above (000[5] is c here rather than d), these are the next steps:
- [ ] Bib team will create test records with different shadowed scenarios in the test database
- [ ] Elaine and Jim will run the records through Jim's script and will send the output to @pgwillia /dev team
- [ ] dev team will run the test ingest through UAT to test to verify the ingest process picks up the deletion. 

tagging @seanluyk for his information.

**Comment by pgwillia** [comment]
@scoHere are a handful of test records that already exist covering four different scenarios.

7925582 - shadowed at the title (record) level
7925585 - item is shadowed using the shadow item checkbox
7925583 - item is in a shadowed location (IN_PROCESS)
7925586 - item is shadowed using the shadow call number checkbox

**Comment by pgwillia** [comment]
oops

**Comment by weiweishi** [comment]
Updated the ticket based on the email conversation. 
@theLinkResolver has provided the following test records:
"Here are a handful of test records that already exist covering four different scenarios.

7925582 - shadowed at the title (record) level
7925585 - item is shadowed using the shadow item checkbox
7925583 - item is in a shadowed location (IN_PROCESS)
7925586 - item is shadowed using the shadow call number checkbox"

Jim discovered that none of their 000[5] were getting set to "d". 

Record Gathering: 
After eliminating UATECHSERV items I eliminated the following Home Locations:
IN_PROCESS,ON_THE_FLY,ON-ORDER(now removed per @theLinkResolver's request) ,UNKNOWN

That meant these items would never be set to "d" because there is no further processing. This is legacy code and the thinking was that they would never be sent. Apparently some of these items did get through to Blacklight and they do need to be deleted. Therefore I removed this line of code and all home locations are processed as of Jan 12. There is no harm in more testing except that we might send "d" titles that they don't even have.

Record processing:
Titles are checked to see if if they need to be set to "d" by 4 different ways represented by Scott's test records.
Shadowed at the title level - Somehow this got missed and I'm sorry. I have now made this the first check as of Jan 12.

Shadowed call number checkbox - If all call numbers of a title are shadowed the title is set to "d". This I believe has always worked but I haven't recently tested it on titles of mixed call numbers.

Shadowed item checkbox - This is part of the next check of shadowed locations. I believe this check has always worked correctly.

Shadowed locations - This is the complex logic that determines whether a title is set to "d". All attached items have to be shadowed for a set to "d".

$allShadowed = "y";
foreach $line (@grp)
  {
  chomp($line);
  next if $line eq "";
  ($ckey2,$seq2,$copy2,$shad2,$homeLoc2,$currentLoc2) = split/\|/,$line;

  if ($line !~ /UNKNOWN/    &&
      $line !~ /MISSING/    &&
      $line !~ /LOST/       &&
      $line !~ /DISCARD/    &&
      $line !~ /LOST-PAID/  &&
      $line !~ /LONGOVRDUE/ &&
      $line !~ /CANC_ORDER/ &&
      $line !~ /ON_THE_FLY/ &&
      $line !~ /LOST-ASSUM/ &&
      $line !~ /LOST-CLAIM/ &&
      $line !~ /INSHIPPING/ &&
      $line !~ /STOR_DARK/  &&
      $line !~ /STOR_RCRF/  &&
      $line !~ /IN_PROCESS/ &&
      $line !~ /ON-ORDER/   &&
      $shad2 != 1)
    {
    $allShadowed = "n";
    }
  }

$shad2 is the checkbox.

A correction was made as of Jan 12. IN_PROCESS and ON-ORDER were added to the if statement. I suppose these were missing because of earlier thinking that they would need to be processed.

Finally an array, @grp = ""; needed to be intialized because it was carrying a previous value.  Should have caught this in previous testing and good practice means always intializing your variables :)

All this is now in service and Saturday's and today's results seem to indicate no problems. 

Also added the following additional shadowed locations: LAST_COPY, PEACERIVER, STONYPT.

**Comment by seanluyk** [comment]
Here's a fresh example: https://search.library.ualberta.ca/catalog/5971717

**Comment by seanluyk** [comment]
Closing with fingers crossed that it doesn't creep in again. Here is Jim's explanation of the cause/solution:

Two major corrections have been made. The cause of missing deletes was lack of awareness due to lack of testing. This big picture testing of the process allowed us to "connect the dots".

Changing the order of reports so that titles are extracted with a Current Location of DISCARD before they are removed. Now that we have the order correct we should shift these reports to the late afternoon and evening, the most stable reliable time. Early mornings are the worst time, susceptible to all the reboot and adutext problems.

Setting the Date Modified to today on Titles that were set to Discard by the "E-Book Deletes" report. Another report that needs to be corrected in the same manner is the "SFX Update" report. Should have this done before Friday. I believe the cataloguers have explained how they set deletes and I will watch for any other sources that could do deletes that are missed.
